[package]
name = "core_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.14"
proc-macro2 = "1.0"
quote = "1"
syn = "1.0"

[dev-dependencies]
sg_core = { path = "../core", package = "core", features = ["figment"] }
trybuild = "1.0"
