[package]
name = "core"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
mongodb = "2.1"
serde = { version = "1.0", features = ["derive"] }
tarpc = { version = "0.27", features = ["serde1"] }
uuid = "0.8"
