[package]
name = "core"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
eyre = "0.6"
futures-util = { version = "0.3", features = ["sink"] }
mongodb = "2.1"
serde = { version = "1.0", features = ["derive"] }
tarpc = { version = "0.27", features = ["serde1"] }
thiserror = "1.0"
tokio-tungstenite = "0.17"
uuid = "0.8"
[dev-dependencies]
tokio = { version = "1.17", features = ["net"] }
