[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sg-core = { package = "core", path = "../core" }

tap                = "1.0"
tracing            = "0.1"
color-eyre         = "0.6"
tracing-subscriber = "0.3"
mod_use            = "0.2"
axum               = "0.4.8"
futures-util       = { version = "0.3" }
serde              = { version = "1.0", features = ["derive"] }
tokio              = { version = "1.17", features = ["rt", "rt-multi-thread", "parking_lot", "time", "net", "macros"] }
mongodb            = { git = "https://github.com/mongodb/mongo-rust-driver.git", rev = "6e7accb50bbfe471f64b290c3a45cda5affbd6fc", features = ["bson-uuid-0_8"] }
figment = { version = "0.10.6", features = ["env"] }
humantime-serde = "1.0.1"
once_cell = "1.9.0"

[dev-dependencies]
figment = { version = "0.10", features = ["test"] }
serde_json = "1.0.79"

[features]

