[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sg-core = { package = "core", path = "../core" }

url                = "2.2.2"
axum               = "0.4.8"
tracing            = "0.1"
futures            = "0.3.21"
mod_use            = "0.2"
color-eyre         = "0.6"
serde_json         = "1.0.79"
humantime-serde    = "1.0.1"
tracing-subscriber = "0.3"
uuid               = { version = "0.8.2", features = ["serde"] }
serde              = { version = "1.0", features = ["derive"] }
figment            = { version = "0.10.6", features = ["env"] }
isolanguage-1      = { version = "0.2", features = ["serde"] }
tokio              = { version = "1.17", features = ["rt", "rt-multi-thread", "time", "macros"] }
mongodb            = { git = "https://github.com/mongodb/mongo-rust-driver.git", rev = "6e7accb50bbfe471f64b290c3a45cda5affbd6fc", features = ["bson-uuid-0_8"] }
jsonwebtoken = "8.0.1"

[dev-dependencies]
figment = { version = "0.10", features = ["test"] }
