on:
  push:
    branches:
      - master

name: sarif

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - run: rustup update && rustup show
        name: Setup Cargo Toolchain 🛎️
      - uses: Swatinem/rust-cache@v1
      - run: cargo install --locked clippy-sarif
        name: Install clippy-sarif 🛎️
      - run:
          cargo clippy --workspace --tests --message-format=json | clippy-sarif > results.sarif
        name: Run Clippy Lints 🔨
      - uses: github/codeql-action/upload-sarif@v1
        name: Upload SARIF file 🚀
        with:
          sarif_file: results.sarif