on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - run: rustup show
        name: Setup Cargo Toolchain 🛎️
      - uses: Swatinem/rust-cache@v1
      - uses: mbrobbel/rustfmt-check@master
        name: Check Code Format (auto fix) 🔧
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/cargo@v1
        name: Run Clippy Lints 🔨
        with:
          command: clippy
          args: --workspace --tests

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      rmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - run: rustup show
        name: Setup Cargo Toolchain 🛎️
      - uses: Swatinem/rust-cache@v1
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-replica-set: rs0
      - uses: actions-rs/cargo@v1
        name: Prepare cargo-nextest 🛎️
        with:
          command: install
          args: --locked cargo-nextest
      - run: cargo nextest run -P ci
        name: Running Tests 🚀