on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout 🛎️
      - uses: dtolnay/rust-toolchain@nightly
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt
      - uses: mbrobbel/rustfmt-check@master
        name: Check Code Format (auto fix) 🔧
        with:
          toolchain: nightly
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout 🛎️
      - run: rustup update && rustup show
        name: Setup Cargo Toolchain 🛎️
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --tests

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      rmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - run: rustup update && rustup show
        name: Setup Cargo Toolchain 🛎️
      - uses: Swatinem/rust-cache@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-replica-set: rs0
          mongodb-version: "6.0"
      - run: cargo install --locked cargo-nextest
        name: Prepare cargo-nextest 🛎️
      - run: cargo nextest run -P ci
        name: Running Tests 🚀
